/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.naufal.view;

import com.naufal.dao.CS_dao;
import com.naufal.model.CS_model;
import com.naufal.model.Print_model;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.PrintJob;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public final class CS_view extends javax.swing.JFrame {

    /**
     * Creates new form CS_view
     */
    CS_dao csdao = new CS_dao();
    Print_model pm = new Print_model();
    List<CS_model> csp;
    //CS_model[] kota;

    public CS_view() {
        initComponents();
        this.Penerima(false);
        this.dataPaket(false);
        btnBaru.setVisible(false);
        txtHarga.setEnabled(false);
        txtPanjang.setEnabled(false);
        txtTinggi.setEnabled(false);
        txtLebar.setEnabled(false);
        this.setLocationRelativeTo(null);
        csp = csdao.getPaket(); // ambil paket masukan kedalam paket
        for (CS_model cS_model : csp) {
            cbxKotaAsal.addItem("" + cS_model);
            cbxKotaPenerima.addItem("" + cS_model);
        }
    }

    public void Penerima(boolean aktifkan) {
        txtNamaPenerima.setEnabled(aktifkan);
        txtAlamatPenerima.setEnabled(aktifkan);
        cbxKotaPenerima.setEnabled(aktifkan);
        txtKodePosPenerima.setEnabled(aktifkan);
        txtProvinsiPenerima.setEnabled(aktifkan);
        txtNoTlpPenerima.setEnabled(aktifkan);
        jPanel2.setEnabled(aktifkan);
    }

    public void dataPaket(boolean aktifkan) {
        cbxJenis.setEnabled(aktifkan);
        txtKilogram.setEnabled(aktifkan);
        cbxLayanan.setEnabled(aktifkan);
        checkBoxDimensi.setEnabled(aktifkan);
        rbtYa.setEnabled(aktifkan);
        rbtTidak.setEnabled(aktifkan);
        rbtTidak.setSelected(true);
//        txtHarga.setEnabled(aktifkan);
        lblHarga.setEnabled(aktifkan);
        cbxPembayaran.setEnabled(aktifkan);
        btnSubmit.setEnabled(aktifkan);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtNamaPengirim = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamarPengirim = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtKodePosPengirim = new javax.swing.JTextField();
        txtProvinsi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNoTlpPengirim = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cbxKotaAsal = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        txtNamaPenerima = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamatPenerima = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        txtKodePosPenerima = new javax.swing.JTextField();
        txtProvinsiPenerima = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNoTlpPenerima = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbxKotaPenerima = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        lblPaket = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbltgl = new javax.swing.JLabel();
        lbltujuan = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbxJenis = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        txtKilogram = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtPanjang = new javax.swing.JTextField();
        txtLebar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        cbxLayanan = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        rbtYa = new javax.swing.JRadioButton();
        rbtTidak = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cbxPembayaran = new javax.swing.JComboBox<>();
        btnSubmit = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        checkBoxDimensi = new javax.swing.JCheckBox();
        lblHarga = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Courier Service");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Courier Service");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pengirim", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel2.setText("Nama Pengirim");

        jLabel3.setText("Alamat Pengirim");

        jLabel4.setText("Kota");

        txtAlamarPengirim.setColumns(20);
        txtAlamarPengirim.setRows(5);
        jScrollPane1.setViewportView(txtAlamarPengirim);

        jLabel5.setText("Kode Pos");

        txtKodePosPengirim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKodePosPengirimFocusLost(evt);
            }
        });

        jLabel6.setText("Provinsi");

        txtNoTlpPengirim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoTlpPengirimFocusLost(evt);
            }
        });

        jLabel7.setText("Telepon Pengirim");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cbxKotaAsal, 0, 160, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKodePosPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(txtNamaPengirim)
                    .addComponent(txtProvinsi)
                    .addComponent(txtNoTlpPengirim))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNamaPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtKodePosPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxKotaAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvinsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTlpPengirim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Penerima", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel8.setText("Nama Penerima");

        jLabel9.setText("Alamat Penerima");

        jLabel10.setText("Kota");

        txtAlamatPenerima.setColumns(20);
        txtAlamatPenerima.setRows(5);
        jScrollPane2.setViewportView(txtAlamatPenerima);

        jLabel11.setText("Kode Pos");

        txtKodePosPenerima.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKodePosPenerimaFocusLost(evt);
            }
        });

        jLabel12.setText("Provinsi");

        txtNoTlpPenerima.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNoTlpPenerimaFocusLost(evt);
            }
        });

        jLabel13.setText("Telepon Penerima");

        cbxKotaPenerima.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxKotaPenerimaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbxKotaPenerima, 0, 160, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtKodePosPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2)
                    .addComponent(txtNamaPenerima)
                    .addComponent(txtProvinsiPenerima)
                    .addComponent(txtNoTlpPenerima))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNamaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(txtKodePosPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxKotaPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProvinsiPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNoTlpPenerima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Paket", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jLabel14.setText("No. Paket              :");

        jLabel15.setText("Tanggal Kirim        :");

        jLabel16.setText("Kota Tujuan          :");

        jLabel17.setText("Jenis Barang         :");

        cbxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Document", "Electronik", "Makanan", "Dll" }));

        jLabel18.setText("Berat                     :");

        txtKilogram.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtKilogramFocusLost(evt);
            }
        });

        jLabel19.setText("Kg");

        jLabel21.setText("Panjang");

        txtPanjang.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPanjangFocusLost(evt);
            }
        });

        txtLebar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLebarFocusLost(evt);
            }
        });

        jLabel22.setText("Cm");

        jLabel23.setText("Tinggi");

        txtTinggi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTinggiFocusLost(evt);
            }
        });

        jLabel24.setText("Lebar");

        jLabel25.setText("Jenis Pengiriman   :");

        cbxLayanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "Ons", "Hds", "Trc", "Sds" }));
        cbxLayanan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxLayananItemStateChanged(evt);
            }
        });

        jLabel26.setText("Asuransi                 :");

        buttonGroup1.add(rbtYa);
        rbtYa.setText("Ya");
        rbtYa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rbtYaItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rbtTidak);
        rbtTidak.setText("Tidak");

        jLabel27.setText("Harga Barang        :");

        txtHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHargaFocusLost(evt);
            }
        });

        jLabel28.setText("Pembayaran          :");

        cbxPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Debit", "Kredit" }));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Total Bayar           :");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotal.setText("Rp.");

        checkBoxDimensi.setText("Dimensi Barang");
        checkBoxDimensi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxDimensiItemStateChanged(evt);
            }
        });

        jLabel20.setText("Harga                    :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbtYa)
                                .addGap(12, 12, 12)
                                .addComponent(rbtTidak))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal))
                            .addComponent(checkBoxDimensi)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(btnBaru)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnSubmit))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel21)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(jLabel23))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(txtLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel22))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(39, 39, 39)
                                            .addComponent(jLabel24))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbltujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbltgl, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                                    .addComponent(lblPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(83, 83, 83))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtKilogram, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lblPaket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(lbltgl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(lbltujuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(cbxLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(lblHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cbxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtKilogram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(7, 7, 7)
                .addComponent(checkBoxDimensi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(26, 26, 26))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(rbtYa)
                    .addComponent(rbtTidak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cbxPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnBaru))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoTlpPengirimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoTlpPengirimFocusLost
        // TODO add your handling code here:
        if (!txtNoTlpPengirim.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan No. Telepon Harus Berupa Angka");
            txtNoTlpPengirim.setText("");
        } else {
            if (txtNamaPengirim.getText().isEmpty() || txtAlamarPengirim.getText().isEmpty() || txtKodePosPengirim.getText().isEmpty() || txtProvinsi.getText().isEmpty() || txtNoTlpPengirim.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Mohon Melengkapi Data Pengirim...", "Kesalahan", 2);
            } else {
                Penerima(true);
            }
        }
    }//GEN-LAST:event_txtNoTlpPengirimFocusLost

    private void txtNoTlpPenerimaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNoTlpPenerimaFocusLost
        // TODO add your handling code here:
        if (!txtNoTlpPenerima.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan No. Telepon Harus Berupa Angka");
            txtNoTlpPenerima.setText("");
        } else {
            if (txtNamaPenerima.getText().isEmpty() || txtAlamatPenerima.getText().isEmpty() || txtKodePosPenerima.getText().isEmpty() || txtProvinsiPenerima.getText().isEmpty() || txtNoTlpPenerima.getText().isEmpty()) {
                JOptionPane.showMessageDialog(rootPane, "Mohon Melengkapi Data Penerima...", "Kesalahan", 2);
            } else {
                lblHarga.setEnabled(true);
                lblHarga.setText(csdao.getHarga("Reguler", cbxKotaPenerima.getSelectedItem() + "") + "");
                dataPaket(true);
                Date dt = new Date();
                SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat noPaket = new SimpleDateFormat("yyddMM");
                lblPaket.setText("CS" + noPaket.format(dt));
                lbltgl.setText(dateFormat.format(dt));
                lbltujuan.setText("" + cbxKotaPenerima.getSelectedItem());
            }
        }
    }//GEN-LAST:event_txtNoTlpPenerimaFocusLost

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        if (!txtKilogram.getText().isEmpty()) {
            System.out.println("YA : " + rbtYa.isSelected());
            if (rbtYa.isSelected()) {
                lblTotal.setText("" + csdao.getHitungPaket(cbxKotaPenerima.getSelectedItem().toString(), cbxLayanan.getSelectedItem().toString(), Integer.parseInt(txtKilogram.getText()), rbtYa.isSelected(), Double.parseDouble(txtHarga.getText())));
                pm = new Print_model(txtNamaPengirim.getText(), cbxKotaAsal.getSelectedItem() + "", txtNamaPenerima.getText(), txtAlamatPenerima.getText(), txtNoTlpPengirim.getText(),
                        cbxKotaPenerima.getSelectedItem() + "", txtNoTlpPenerima.getText(), txtProvinsiPenerima.getText(), lblPaket.getText(), lbltgl.getText(), cbxJenis.getSelectedItem() + "",
                        lblHarga.getText(), txtKilogram.getText(), rbtYa.getText(), txtHarga.getText(), cbxPembayaran.getSelectedItem() + "", lblTotal.getText());
            } else {
                lblTotal.setText("" + csdao.getHitungPaket(cbxKotaPenerima.getSelectedItem().toString(), cbxLayanan.getSelectedItem().toString(), Integer.parseInt(txtKilogram.getText()), rbtYa.isSelected(), 0.0));
                pm = new Print_model(txtNamaPengirim.getText(), cbxKotaAsal.getSelectedItem() + "", txtNamaPenerima.getText(), txtAlamatPenerima.getText(), txtNoTlpPengirim.getText(),
                        cbxKotaPenerima.getSelectedItem() + "", txtNoTlpPenerima.getText(), txtProvinsiPenerima.getText(), lblPaket.getText(), lbltgl.getText(), cbxJenis.getSelectedItem() + "",
                        lblHarga.getText(), txtKilogram.getText(), rbtTidak.getText(), "0", cbxPembayaran.getSelectedItem() + "", lblTotal.getText());
            }
            int hasil = JOptionPane.showConfirmDialog(rootPane, "Anda Ingin Cetak Resi?");
            System.out.println("Hasil" + hasil);// juka yes 0, jika no 1, cancel 2
            if (hasil == 0) {
                PrintJob p = getToolkit().getPrintJob(this, "Report", null);
                Graphics g = p.getGraphics();
                g.setFont(new Font("Serif", Font.BOLD, 18));
                g.drawString("Resi Courier Service", 75, 50);
                g.drawLine(75, 75, 500, 75);
                g.setFont(new Font("Serif", Font.BOLD, 12));
                // g.drawString("Title", Kepinggir, Kebawah);
                // Sebelah Kiri
                g.drawString("Kota Asal", 100, 100);
                g.drawString(" : " + pm.getKotaAsal(), 200, 100);
                g.drawString("Nomor Paket", 100, 125);
                g.drawString(" : " + pm.getNomorPaket(), 200, 125);
                // Sebelah Kiri

                // Sebalah Kanan
                g.drawString("Kota Tujuan", 350, 100);
                g.drawString(" : " + pm.getKotaTujuan(), 420, 100);
                g.drawString("Service", 350, 125);
                g.drawString(" : " + pm.getJenisPengiriman(), 420, 125);
                // Sebalah Kanan

                //Dibawah Bagian Pengirim
                g.drawLine(75, 135, 500, 135);
                g.setFont(new Font("Serif", Font.BOLD, 14));
                g.drawString("Pengirim", 100, 150);
                g.setFont(new Font("Serif", Font.PLAIN, 12));
                g.drawString("Nama", 100, 170);
                g.drawString(" : " + pm.getNamaPengirim(), 160, 170);
                g.drawString("Alamat", 100, 190);
                g.drawString(" : " + pm.getKotaAsal(), 160, 190);
                g.drawString("Kota", 100, 210);
                g.drawString(" : " + pm.getKotaAsal(), 160, 210);
                g.drawString("Tlp", 100, 230);
                g.drawString(" : " + pm.getNoTlpPengirim(), 160, 230);
                //Dibawah Bagian Pengirim Sebelah Kiri

                //Dibawah Bagian Penerima Sebelah Kanan
                g.setFont(new Font("Serif", Font.BOLD, 14));
                g.drawString("Penerima", 350, 150);
                g.setFont(new Font("Serif", Font.PLAIN, 12));
                g.drawString("Nama", 350, 170);
                g.drawString(" : " + pm.getNamaPenerima(), 410, 170);
                g.drawString("Alamat", 350, 190);
                g.drawString(" : " + pm.getAlamatTujuan(), 410, 190);
                g.drawString("Kota", 350, 210);
                g.drawString(" : " + pm.getKotaTujuan(), 410, 210);
                g.drawString("Tlp", 350, 230);
                g.drawString(" : " + pm.getNoTlpPenerima(), 410, 230);
                g.drawLine(75, 250, 500, 250);
                //Dibawah Bagian Penerima Sebelah Kanan

                // g.drawString("Title", Kepinggir, Kebawah);
                //Dibawah Bagian Harga
                g.setFont(new Font("Serif", Font.BOLD, 12));
                g.drawString("Berat Paket", 320, 270);
                g.drawString(" : " + pm.getBerat(), 420, 270);
                g.drawString("Asuransi", 320, 290);
                g.drawString(" : " + pm.getAsuransi(), 420, 290);
                g.drawString("Harga Barang", 320, 310);
                g.drawString(" : " + pm.getHargaBarang(), 420, 310);
                g.drawString("Pembayaran", 320, 330);
                g.drawString(" : " + pm.getPembayaran(), 420, 330);
                g.drawString("Total", 320, 350);
                g.drawString(" : " + pm.getTotal(), 420, 350);
                //Dibawah Bagian Harga

                p.end();
                btnBaru.setVisible(true);
            } else if (hasil == 1) {
                btnBaru.setVisible(true);
            } else {
                btnBaru.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Mohon isi berat barang!", "Kesalahann", 2);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void rbtYaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rbtYaItemStateChanged
        // TODO add your handling code here:
        if (rbtYa.isSelected()) {
            txtHarga.setEnabled(true);
        } else {
            txtHarga.setText("");
            txtHarga.setEnabled(false);
        }
    }//GEN-LAST:event_rbtYaItemStateChanged

    private void checkBoxDimensiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxDimensiItemStateChanged
        if (checkBoxDimensi.isSelected()) {
            txtPanjang.setEnabled(true);
            txtTinggi.setEnabled(true);
            txtLebar.setEnabled(true);
        } else {
            txtPanjang.setEnabled(false);
            txtTinggi.setEnabled(false);
            txtLebar.setEnabled(false);
        }
    }//GEN-LAST:event_checkBoxDimensiItemStateChanged

    private void cbxLayananItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxLayananItemStateChanged
        System.out.println("Harga : " + csdao.getHarga("" + cbxLayanan.getSelectedItem(), cbxKotaPenerima.getSelectedItem() + ""));
        lblHarga.setText("" + csdao.getHarga("" + cbxLayanan.getSelectedItem(), cbxKotaPenerima.getSelectedItem() + ""));
    }//GEN-LAST:event_cbxLayananItemStateChanged

    private void cbxKotaPenerimaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxKotaPenerimaItemStateChanged
        // TODO add your handling code here:
        if (!txtNoTlpPenerima.getText().isEmpty()) {
            lblHarga.setText("" + csdao.getHarga("" + cbxLayanan.getSelectedItem(), cbxKotaPenerima.getSelectedItem() + ""));
        }
        cbxLayanan.setSelectedItem("Reguler");
    }//GEN-LAST:event_cbxKotaPenerimaItemStateChanged

    private void txtKodePosPengirimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKodePosPengirimFocusLost
        // TODO add your handling code here:
        if (!txtKodePosPengirim.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Kode Pos Harus Berupa Angka");
            txtKodePosPengirim.setText("");
        }
    }//GEN-LAST:event_txtKodePosPengirimFocusLost

    private void txtKodePosPenerimaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKodePosPenerimaFocusLost
        // TODO add your handling code here:
        if (!txtKodePosPenerima.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Kode Pos Harus Berupa Angka");
            txtKodePosPenerima.setText("");
        }
    }//GEN-LAST:event_txtKodePosPenerimaFocusLost

    private void txtKilogramFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtKilogramFocusLost
        // TODO add your handling code here:
        if (!txtKilogram.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Berat Harus Berupa Angka");
            txtKilogram.setText("");
        }
    }//GEN-LAST:event_txtKilogramFocusLost

    private void txtPanjangFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPanjangFocusLost
        // TODO add your handling code here:
        if (!txtPanjang.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Ukuran Panjang Harus Berupa Angka");
            txtPanjang.setText("");
        }
    }//GEN-LAST:event_txtPanjangFocusLost

    private void txtTinggiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTinggiFocusLost
        // TODO add your handling code here:
        if (!txtTinggi.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Ukuran Tinggi Harus Berupa Angka");
            txtTinggi.setText("");
        }
    }//GEN-LAST:event_txtTinggiFocusLost

    private void txtLebarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLebarFocusLost
        // TODO add your handling code here:
        if (!txtLebar.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Ukuran Lebar Harus Berupa Angka");
            txtLebar.setText("");
        }
    }//GEN-LAST:event_txtLebarFocusLost

    private void txtHargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHargaFocusLost
        // TODO add your handling code here:
        if (!txtHarga.getText().matches("[0-9]*")) {
            JOptionPane.showMessageDialog(rootPane, "Maaf Inputan Harga Barang Harus Berupa Angka");
            txtHarga.setText("");
        }
    }//GEN-LAST:event_txtHargaFocusLost

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        this.Penerima(false);
        this.dataPaket(false);
        btnBaru.setVisible(false);
        txtHarga.setEnabled(false);
        txtPanjang.setEnabled(false);
        txtTinggi.setEnabled(false);
        txtLebar.setEnabled(false);
    }//GEN-LAST:event_btnBaruActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CS_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CS_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CS_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CS_view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CS_view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxJenis;
    private javax.swing.JComboBox cbxKotaAsal;
    private javax.swing.JComboBox cbxKotaPenerima;
    private javax.swing.JComboBox<String> cbxLayanan;
    private javax.swing.JComboBox<String> cbxPembayaran;
    private javax.swing.JCheckBox checkBoxDimensi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblPaket;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lbltgl;
    private javax.swing.JLabel lbltujuan;
    private javax.swing.JRadioButton rbtTidak;
    private javax.swing.JRadioButton rbtYa;
    private javax.swing.JTextArea txtAlamarPengirim;
    private javax.swing.JTextArea txtAlamatPenerima;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtKilogram;
    private javax.swing.JTextField txtKodePosPenerima;
    private javax.swing.JTextField txtKodePosPengirim;
    private javax.swing.JTextField txtLebar;
    private javax.swing.JTextField txtNamaPenerima;
    private javax.swing.JTextField txtNamaPengirim;
    private javax.swing.JTextField txtNoTlpPenerima;
    private javax.swing.JTextField txtNoTlpPengirim;
    private javax.swing.JTextField txtPanjang;
    private javax.swing.JTextField txtProvinsi;
    private javax.swing.JTextField txtProvinsiPenerima;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
